name: Actions

on:
  push:
    branches:
      - main
jobs:
  actions:
    name: Actions
    outputs:
      salida: "Hola Actions"
    runs-on: ubuntu-latest
    steps:
      - name: mensaje
        id: mensaje
        run: echo "mensaje=Hola MUndo" >> $GITHUB_OUTPUT
      - name: Working directory
        run: ls -la
      - name: Checkout code
        uses: actions/checkout@v2 #Autor/action@versión
      - name: Working directory
        run: ls -la
      - name: Imprimiendo mensaje
        run: echo "Mensaje ${{ steps.mensaje.outputs.mensaje }}"
  mensajes:
    name: Mensajes
    runs-on: ubuntu-latest
    needs: actions
    env:
      salida: ${{ needs.actions.outputs.salida }}
    steps:
      - name: Imprimiendo mensaje
        run: echo "Mensaje desde el job mensajes ${{ env.salida }}"
