name: Actions

on:
  push:
    branches:
      - main
jobs:
  actions:
    name: Actions
    runs-on: ubuntu-latest
    steps:
      - name: mensaje
        id: mensaje
        run: echo "mensaje=Hola MUndo" >> $GITHUB_OUTPUTS
      - name: Working directory
        run: ls -la        
      - name: Checkout code
        uses: actions/checkout@v2 #Autor/action@versión
      - name: Working directory
        run: ls -la
      - name: Imprimiendo mensaje
        run: echo "Mensaje: ${{ steps.mensaje.outputs.mensaje }}"
