name: Actions

on:
  push:
    branches:
      - main
jobs:
  actions:
    name: actions
    outputs:
      salida: "Hola Actions"
    runs-on: ubuntu-latest
    steps:
      - name: mensaje
        id: mensaje
        run: echo "mensaje=Hola MUndo" >> $GITHUB_OUTPUT
      - name: Working directory
        run: ls -la
      - name: Checkout code
        uses: actions/checkout@v2 #Autor/action@versión
      - name: Working directory
        run: ls -la
      - name: Imprimiendo mensaje
        run: echo "Mensaje ${{ steps.mensaje.outputs.mensaje }}"
  mensajes:
    name: Mensajes
    runs-on: ubuntu-latest
    needs: actions
    env:
      salida: ${{ needs.actions.outputs.salida }}
    steps:
      - name: Imprimiendo mensaje
        run: echo "Mensaje desde el job mensajes ${{ env.salida }}"
  artefacto:
    name: artefacto
    runs-on: ubuntu-latest
    steps:
      - name: Crear un archivo
        run: echo "Este es un archivo de prueba" > archivo.txt
      - name: Subir el archivo como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-prueba
          path: archivo.txt
  descargar:
    name: Descargar artefacto
    runs-on: ubuntu-latest
    needs: artefacto
    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-prueba
      - name: Listar archivos descargados
        run: ls -la
      - name: Leer contenido del archivo
        run: cat archivo.txt
