name: deploy
on:
  push:
    branches:
      - clase3
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
          - name: Print secret
            run: echo "El secreto es ${{ secrets.REPO_SECRET }}"