name: deploy
on:
  push:
    branches:
      - clase3
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        run: echo "El secreto es ${{ secrets.REPO_SECRET }}"
      - name: Print variable
        run: echo "La variable es ${{ vars.ENV_VAR }}"
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
