name: Hola mundo #Nombre
on: #Disparador, puede ser push, pull_request, etc.
  push:
    branches:
      - main #Rama a la que se le hará push
jobs:
  deploy: #Nombre del trabajo
    name: Deploy #Nombre del trabajo
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' #Condición para ejecutar el trabajo
    runs-on: ubuntu-latest #Máquina virtual donde se ejecutará el trabajo
    steps:
      - name: Checkout code
        run: echo "Checking out code..."
      - name: Correr migraciones
        run: echo "Correr migraciones..."
      - name: Generar binarios
        run: echo "Generar binarios..."
      - name: Publicar website
        run: echo "Publicar website..."
      - name: Enviar notificación
        run: echo "Enviar notificación..."
  notifications: #Nombre del trabajo
    name: Notifications #Nombre del trabajo
    depends-on: deploy #Dependencia del trabajo anterior
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest #Máquina virtual donde se ejecutará el trabajo
    steps:
      - name: Enviar correo electrónico
        run: echo "Enviar correo electrónico..."      
